### ISSUE TITLE
Topic lead paragraph is not displayed

### ISSUE THREAD

**Issue by OndraZizka** [redhatcz/Thesis-management-system#104] opened 2016-07-27 06:02 UTC
STR:
1) Create a topic, put something in the lead paragraph
2) It's not displayed when viewing the topic.

**Comment by sbunciak** [comment] 2016-07-27 09:51
I believe it's an intended behavior, and I find it all-right. Displaying the lead paragraph when viewing topic details seems redundant to me as you see the complete description of the topic. Thoughts @jcechace @VaclavDedik ?

**Comment by VaclavDedik** [comment] 2016-07-28 12:15
Yeah, I am not sure, maybe it would be better to display it, or make it more apparent that it's not displayed. The name "lead paragraph" seems to imply it will be displayed as the first paragraph. So either displaying it or maybe renaming it to something like "short description" or something like that would be a good idea.

**Comment by jcechace** [comment] 2016-07-28 12:38
Well the name is not really confusing provided you know that lead paragraph is English term for [perex](https://cs.wikipedia.org/wiki/Perex) -- which is not supposed to be the "first" paragraph. Which of course might not often be the case. 

Because of this I agree with the change. However displaying it might have undesired effect on existing topics -- e.g. duplication of this "leading paragraph".  Renaming it to "short description" would be more appropriate.

**Comment by sbunciak** [comment] 2016-07-28 12:48
+1 for renaming

**Comment by VaclavDedik** [comment] 2016-09-09 12:06
Fixed by #128

**Closed by VaclavDedik** 2016-09-09 12:06 UTC
